blank_issues_enabled: false
contact_links:
  - name: Discussions on GitHub 💬
    url: https://github.com/callstack/react-native-local-notifications/discussions
    about: If this library works as promised but you need help, please ask questions there.
